name: HIFI-Telegram-Signals

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 min UTC
  workflow_dispatch:         # manual button in UI

jobs:
  signal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests pandas

      - name: Run signal bot
        run: python signal_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT:  ${{ secrets.TELEGRAM_CHAT }}
